### ISSUE TITLE
Incompleteness of the simulation code

### ISSUE THREAD

**Issue by FeihonYu** [DxChen0126/time_varying_GT#1]
I try to source your code and find you may forget to upload the "process_sim.R" R file in your code. 
Wish you can upload it! Thank you

**Comment by DxChen0126** [comment]
Hi, thank you for noticing this. I have put the "process_sim.R" code under the simulation subfolder. Note that in previous version I only uploaded "process_sim_incomplete_expo.R", they are very similar.

**Comment by FeihonYu** [comment]
yes, I notice that. thank you for your help~
